# Generated by Django 5.1.2 on 2024-10-24 04:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('procedencia', models.CharField(max_length=25)),
                ('fechaInicio', models.DateField()),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('correo', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator(message='Introduce un correo válido.')])),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotosEmpleados/')),
                ('rol', models.CharField(max_length=254)),
                ('Salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipoNomina', models.CharField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['nombres'],
            },
        ),
        migrations.CreateModel(
            name='DocumentosEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.ImageField(blank=True, null=True, upload_to='documentosEmpleados/contratos')),
                ('actaNacimiento', models.ImageField(blank=True, null=True, upload_to='documentosEmpleados/actaNacimiento')),
                ('identificacion', models.ImageField(blank=True, null=True, upload_to='documentosEmpleados/identificacion')),
                ('comDomicilio', models.ImageField(blank=True, null=True, upload_to='documentosEmpleados/comDomicilio')),
                ('seguroSocial', models.ImageField(blank=True, null=True, upload_to='documentosEmpleados/SeguroSocial')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleados')),
            ],
            options={
                'verbose_name': 'Documento de Empleado',
                'verbose_name_plural': 'Documentos de Empleados',
            },
        ),
    ]
