# Generated by Django 5.1.2 on 2024-10-24 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departamentos', '0001_initial'),
        ('Empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleados_en_departamento', to='Departamentos.departamento'),
        ),
    ]
