# Generated by Django 4.2.4 on 2024-10-25 03:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empleados', '0002_empleados_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField(auto_now_add=True)),
                ('fechaFin', models.DateField(auto_now_add=True)),
                ('pagoNomina', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.BooleanField(default=False)),
                ('diasPagadas', models.IntegerField()),
                ('empelado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleados_en_departamento', to='Empleados.empleados')),
            ],
        ),
    ]
