# Generated by Django 4.2.4 on 2024-10-25 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0002_empleados_departamento'),
        ('Nomina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominas',
            name='empelado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleados_en_nominas', to='Empleados.empleados'),
        ),
    ]
