# Generated by Django 4.2.4 on 2024-10-25 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('unbicacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='materiaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('incioZafra', models.DateField(auto_now_add=True)),
                ('finZafra', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procesos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('areas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas_en_procesos', to='MateriaPrima.area')),
                ('materia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materia_utizada_en_procesos', to='MateriaPrima.materiaprima')),
            ],
        ),
    ]
