# Generated by Django 4.2.4 on 2024-10-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
                ('razonSocial', models.CharField(max_length=254)),
                ('rfc', models.CharField(max_length=254)),
                ('direecion', models.CharField(max_length=254)),
                ('telefono', models.CharField(max_length=254)),
                ('correo', models.CharField(max_length=254)),
                ('vision', models.CharField(max_length=254)),
                ('valores', models.CharField(max_length=254)),
                ('mision', models.CharField(max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
            ],
        ),
    ]
