# Generated by Django 4.2.4 on 2024-10-25 03:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MateriaPrima', '0001_initial'),
        ('Empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=254)),
                ('rfc', models.CharField(max_length=254)),
                ('razonSocial', models.CharField(max_length=254)),
                ('direccion', models.CharField(max_length=254)),
                ('pagina', models.CharField(max_length=254)),
                ('telefono', models.CharField(max_length=13)),
                ('caracterPersona', models.CharField(max_length=254)),
                ('materiaP', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes_o_provedores_en_contacto', to='MateriaPrima.materiaprima')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
                ('telefono', models.CharField(max_length=13)),
                ('correo', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator(message='Introduce un correo válido.')])),
                ('tipo', models.CharField(max_length=254)),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes_o_provedores_en_contacto', to='Empresa.personas')),
            ],
        ),
    ]
